### ISSUE TITLE
Custom renderer breaks bool checkboxes.

### ISSUE THREAD

**Issue by tjcuddihy** [jrowen/rhandsontable#147] opened 2017-01-30 20:06 UTC
Hi @jrowen,

I'm looking to do some custom conditional formatting on a table that I want editable, however, using the renderer with an R parameter breaks the behaviour of the boolean checkboxes.
See your documentation [here](https://jrowen.github.io/rhandsontable/#custom_renderer) for an example. You can see under "Custom Renderer using an R Parameter" that the check boxes disappear and char(bool) is shown instead. Additionally, this field is no longer editable.

**Comment by jrowen** [comment] 2017-02-06 15:17
Your custom function will need to use a different renderer based on the data type (see options [here](https://github.com/handsontable/handsontable/blob/715c3deeb16e97ed867439c766598517d64429f0/src/cellTypes.js)).

Thanks for pointing out the discrepancy on the doc page.  We'll get a fix out there shortly.

**Comment by marciz** [comment] 2017-02-08 19:58
Custom formatting also on empty table creates table of "NA". 
Without formatting "NA" are not visible

```
library(shiny)
library(rhandsontable)

ui <- shinyUI(fluidPage(
  titlePanel("Handsontable"),
  sidebarLayout(
    sidebarPanel(
      helpText("Handsontable demo output. Column add/delete does work ",
               "for tables with defined column properties, including type."),
      radioButtons("useType", "Use Data Types", c("TRUE", "FALSE"))
      ),
    mainPanel(
      rHandsontableOutput("hot", width = 350)
    )
  )
))

server <- function(input, output, session) {
  # this caching step is no longer necessary
  # it was left as an example
  values = reactiveValues()
  
  data = reactive({
    if (!is.null(input$hot)) {
      DF = hot_to_r(input$hot)
    } else {
      if (is.null(values[["DF"]]))
        # DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
        #                 dt = seq(from = Sys.Date(), by = "days", length.out = 10),
        #                 stringsAsFactors = F)
      DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = F)[FALSE,][1:10,]
      else
        DF = values[["DF"]]
    }
    
    values[["DF"]] = DF
    DF
  })
  
  output$hot <- renderRHandsontable({
    DF = data()
    if (!is.null(DF))
        rhandsontable(DF, useTypes = as.logical(input$useType), stretchH = "all") %>%
          hot_cols(renderer = "function (instance, td, row, col, prop, value, cellProperties) {
                   Handsontable.renderers.NumericRenderer.apply(this, arguments);
                   if (col > 2) {
                   td.style.background = 'lightgrey';
                   }}")
  })
}

shinyApp(ui = ui, server = server)

```

**Comment by jrowen** [comment] 2017-02-20 21:52
That is by design.  The custom renderer shows NA as and empty string, so if you create your own custom render, you'll need to implement similar logic (or call the custom render from rhandsontable).

**Comment by jrowen** [comment] 2017-05-21 14:23
Closing, but please let me know if you still have questions.

**Closed by jrowen** 2017-05-21 14:23 UTC
