### ISSUE TITLE
Getting data from hot table in shiny

### ISSUE THREAD

**Issue by jpmarindiaz** [jrowen/rhandsontable#13] opened 2015-04-14 19:36 UTC
Hi, yesterday this code was working fine for me. Now I get some an error when I run the shiny app and try to change some value in the hot table.
```
Error: attempt to set 'colnames' on an object with less than two dimensions
```
This is the app:
```
library(shiny)
library(rhandsontable)

ui = shinyUI(fluidPage(
  
  titlePanel("Handsontable"),
  
  sidebarLayout(
    sidebarPanel(
      rHandsontableOutput("hot")
    ),
    mainPanel(
      verbatimTextOutput("debug"),
      #tableOutput("table"),
      br()
    )
  )
))

server = function(input, output) {
  
  data <- reactive({
    if (is.null(input$hot)) {
      DF = data.frame(val = 1:10, bool = TRUE, nm = LETTERS[1:10],
                      dt = seq(from = Sys.Date(), by = "days", length.out = 10),
                      stringsAsFactors = F)
    } else {
      DF = hot_to_r(input$hot)
    }
    DF
  })
    
  output$hot <- renderRHandsontable({
    DF <- data()
    rhandsontable(DF, useTypes = FALSE, selectCallback = TRUE)
  })
  
  
  output$table <- renderTable({data()})
  
  ### DEBUG
  output$debug <- renderPrint({
    str(input$hot_select$select)
  })  
}

shinyApp(ui = ui, server = server)
```

It would be great if you could take a look, thanks!

**Comment by jrowen** [comment] 2015-04-15 00:12
I just pushed a bunch of updates, and your example appears to be working fine.  Could you please pull down the latest version (0.0.2) and let me know if you are still running into errors?

**Comment by jpmarindiaz** [comment] 2015-04-15 02:06
Unfortunately I am getting the same Error:
```
Error: attempt to set 'colnames' on an object with less than two dimensions
```
Here is my session info
```
 sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.2 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhandsontable_0.0.2 shiny_0.11.1.9004  

loaded via a namespace (and not attached):
 [1] digest_0.6.8      htmltools_0.2.6   htmlwidgets_0.3.3 httpuv_1.3.2     
 [5] jsonlite_0.9.16   magrittr_1.5      mime_0.3          R6_2.0.1         
 [9] Rcpp_0.11.5       rstudio_0.98.1091 rstudioapi_0.3.1  tools_3.1.3      
[13] xtable_1.7-4      yaml_2.1.13
```

**Comment by jrowen** [comment] 2015-04-15 02:30
I'm running the same versions except it's on Linux and rstudio is v0.98.1103.  Can you try using traceback to find the source of the error?

**Comment by jpmarindiaz** [comment] 2015-04-15 02:35
I am not familiar with traceback, but I will try to take a look.
I also tried it in my linux machine and I get the same error.

**Comment by jpmarindiaz** [comment] 2015-04-15 02:49
I was playing around and noticed that the error only shows up only when I use: `useTypes = FALSE`.
If I use `rhandsontable(DF, selectCallback = TRUE)` in the example above I don't see the `colnames` error anymore.

**Comment by jrowen** [comment] 2015-04-15 04:55
The error might be coming from the function that creates an R data.frame
from the widget data.  You could try to use debug(toR) to step through the
conversion and identify the problem.  I'm still unable to reproduce the
error.

**Comment by jrowen** [comment] 2015-04-17 02:13
I just pushed some updates related to column and row add/removes.  Previously, when editing columns and rows, I saw a message similar to the one you mentioned.  Could you retest with this latest update and let me know if you are still running into problems?  Thanks.

**Comment by jrowen** [comment] 2015-04-24 00:25
I'm going to close this issue, but please re-open if you are still seeing errors.

**Closed by jrowen** 2015-04-24 00:25 UTC
