### ISSUE TITLE
Error when pasting new rows

### ISSUE THREAD

**Issue by martinv13** [jrowen/rhandsontable#138] opened 2016-12-28 00:21 UTC
Hi,
`hot_to_r` fails when pasting rows from Excel results in creating new rows.
To reproduce, you can try it with your example:

`shiny::runGitHub("rhandsontable", "jrowen", 
              subdir = "inst/examples/rhandsontable_portfolio")`

Paste an array with more rows than the rhandsontable currently has. An error is triggered in `hot_to_r`:
```
Warning: Error in row.names<-.data.frame: invalid 'row.names' length
Stack trace (innermost first):
    88: row.names<-.data.frame
    87: row.names<-
    86: rownames<-
    85: <Anonymous>
    84: do.call
    83: hot_to_r
    82: is.data.table
    81: setDT
```
I tried to fix it modifying your code, with no luck so far...
Thank you!

**Comment by jrowen** [comment] 2017-01-09 12:40
Did you try this with [`handsontable`](https://handsontable.com/) (see [examples here](https://handsontable.com/examples.html))?

**Comment by martinv13** [comment] 2017-01-09 16:55
With `handsontable` the table is extended without any problem when you paste new rows.
Whith `rhandsontable`, `hot_to_r` fails when new rows are added. It does not seem to work either when you create new lines using the bottom right square of a cell to extend it beyond the limits of the `rhandsontable` (the error is different though, you enter some kind of infinite loop update between R and the browser).
Thanks

**Comment by wurzerj** [comment] 2017-02-13 17:21
I am facing the same issue. From my point of view the bug is in `rhandsontable:::toR`: 
- At the very bottom of the function you assign the row names (`rownames(out) = rowHeaders`).
- If you add a new line to an existing table and parse the content with `rhandsontable::hot_to_r`, it seems that `x$params$rRowHeaders` only contains the old row headers and misses any value for the new row.
- Due to non-matching dimensions `rhandsontable:::toR` crashes.
- Interestingly there is some code to prevent this to happen if you add columns, but not for rows.

A temporary workaround is to manually fix this parameter with before executing `rhandsontable::hot_to_r(x)`:

`x$params$rRowHeaders <- as.character(seq_len(length(x$data)))`

**Comment by hjfischer** [comment] 2017-03-01 00:16
It probably goes without saying, but the `hot_to_r` issue also occurs when rows are removed.

**Comment by jrowen** [comment] 2017-03-01 12:32
I'm using the latest dev version and not running into any problems with the example noted above.  I can add a new row and update cells, each time seeing 'Event' printed to the console.  Would you mind trying the dev version and letting me know if you still run into an error?

**Comment by hjfischer** [comment] 2017-03-01 16:01
Here is another example that highlights the issue as in the first post.  Click `Save` after adding or deleting a row, and the `Warning: Error in row.names<-.data.frame: invalid 'row.names' length` error will appear.  I'm using the latest dev version.

```{R}
library(shiny)
library(rhandsontable)

ui <- function() {
  fluidRow(actionButton(inputId = "download", label = "Save")),
  fluidRow(rHandsontableOutput("tab"))
}

server <- function(input, output, session) {
  output$tab <- renderRHandsontable({
    rhandsontable(mtcars)
  })
  
  save <- observe({
    if(input$download == 0) return()
    saveRDS(hot_to_r(input$tab), file = "test.rds")
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by wurzerj** [comment] 2017-03-13 16:42
Tested the latest dev version:
- I can confirm, that reactivity is working as it should (in contrast to the CRAN version)
- Unfortunately hot_to_r crashes, as described in hjfischer's last post

**Comment by jrowen** [comment] 2017-03-14 14:38
I just pushed an update that should fix the row naming problem.  You may need to update your app to use the following pattern when referring to the table:
```
  output$tab <- renderRHandsontable({
    if (!is.null(input$tab)) {
      DF = hot_to_r(input$tab)
    } else {
      DF = mtcars
    }

    rhandsontable(DF)
  })
```
Without these steps, table updates won't be in sync with the data R object mapping.  At some point, it would be ideal to move this logic to JavaScript and avoid the R step.

**Comment by jrowen** [comment] 2017-05-21 15:00
Closing, but please let me know if you still have questions.

**Closed by jrowen** 2017-05-21 15:00 UTC
