### ISSUE TITLE
Automatic addition of an extra row

### ISSUE THREAD

**Issue by Rustastra** [jrowen/rhandsontable#95] opened 2016-07-27 17:36 UTC
Hello,

I was just wondering if it was possible to disable the addition of an extra row when dragging the values down (with the corner of a cell)?
Thanks a lot!

**Comment by jrowen** [comment] 2016-08-01 15:17
I'm unable to reproduce this behavior.  Could you share an example?

**Comment by bklingen** [comment] 2016-08-01 15:46
Go to https://artofstat.shinyapps.io/rhandsontableandshiny/ and click on the second row (highlight the entire second row) and then grab the corner and pull it down. This will add an extra  empty row. The ui.r and server.r files for this app are:
```{r}
library(rhandsontable)
shinyUI(fluidPage(
  titlePanel("Edit Table"),
  rHandsontableOutput("hot")
))

shinyServer(function(input, output, session) {
  output$hot = renderRHandsontable({
    if (!is.null(input$hot)) {
      DF = hot_to_r(input$hot)
    } else {
      DF = data.frame(Var1=c("one","two"), 
                      Var2=3:4, 
                      Var3=c(TRUE,FALSE),
                      stringsAsFactors=FALSE)
    }
    rhandsontable(DF) %>% 
      hot_table(highlightCol = TRUE, highlightRow = TRUE)
  })
})

**Comment by jrowen** [comment] 2016-08-02 21:57
Can you determine the source of the extra row?  Is it added before or after
the data is passed back to R?

**Comment by Rustastra** [comment] 2016-08-04 13:59
It automatically adds an empty or NA row. So e.g. we have a data frame with 10 rows. If I drag down to row 10, a row 11 is added, and it is NA.

**Comment by jrowen** [comment] 2016-08-15 23:05
The row addition appears to be part of handsontable (see the sample table here, dragdown to add a row: http://docs.handsontable.com/0.26.1/tutorial-quick-start.html).  The widget appears to be a little aggressive with creating new rows, even when `minSpareRows=0`.

As a temporary fix, I might be able to remove these rows in `hot_to_r`.

**Comment by jrowen** [comment] 2016-11-15 20:07
Adding the parameter below to `rhandsontable` may fix this issue.
```
http://docs.handsontable.com/0.29.0/demo-drag-down.html
```
See also http://docs.handsontable.com/0.29.0/demo-drag-down.html

**Comment by KasperSkytte** [comment] 2017-09-28 07:32
Had the same issue, where an extra empty row was added when dragging to the las row. The above fixed it, thanks!

**Comment by jrowen** [comment] 2018-01-04 19:08
Closing as there seems to be a workaround.

**Closed by jrowen** 2018-01-04 19:08 UTC
